theme: jekyll-theme-minimal
#theme: jekyll-theme-merlot

show_downloads: false
title: Hub-O-Matic
description: Automatic Updating for macOS apps

is_project_page: false

github:
  is_project_page: false

